### ISSUE TITLE
Create Code style guidelines to improve consistency.

### ISSUE THREAD

**Issue by ChasingLogic** [ChasingLogic/cardinal#61]
@growlove add any suggestions you have here and I'll prettify the results and put them in the wiki.

Some of my personal rules

Any Anonymous function should use the => form

Whenever appropriate (i.e. performing any logic other than calling another named function) give an inline function a name. 

if statements should always have {} and should never be all on one line. i.e.
Not This:
```
if(err) { return err }
```
Instead this:
```
if(err) {
    return err;
}
```

Use tab characters instead of spaces. If using spaces use 4 spaces. <- This is for my sanity use tab characters if you're nuts and want to have two space tabs but otherwise be a well adjusted adult and use 4 spaces.

Always prefer being extremely explicit instead of implicit.

**Comment by growlove** [comment]
I mostly just reference these two:

https://github.com/felixge/node-style-guide
https://github.com/airbnb/javascript

I'm not too particular about most things though. I like what you have so far, and I'll switch to 4 spaces, just for you :P

**Comment by growlove** [comment]
I think we should follow the lisp-case lowercase-seperated-by-hyphens that seems to be pretty standard for most of the node/js community for file and directory naming. We currently have some mixing between camel casing, snake casing, and lisp casing, and it's kind of confusing.

**Comment by ChasingLogic** [comment]
Fixing it I agree with all of this. I used some of the jshint config from the first link

**Comment by growlove** [comment]
Closing as we have automatic syntax verification through npm test now.
