### ISSUE TITLE
Move all mongojs code to promised-mongo

### ISSUE THREAD

**Issue by ChasingLogic** [ChasingLogic/cardinal#64]
@growlove this is an awesome find and is EXACTLY what i was wishing mongojs did. I'm rewriting all of the existing mongojs code to use it instead.

**Comment by growlove** [comment]
Makes it so much freaking easier to work with. 

I really need to get into the habit of opening issues about things I find or start using.

**Comment by growlove** [comment]
Closing because I believe everything is now using promised-mongo.
