### ISSUE TITLE
Fix setup.js

### ISSUE THREAD

**Issue by ChasingLogic** [ChasingLogic/cardinal#68]
@growlove I'm working on making this actually correct.....

**Comment by growlove** [comment]
I made a branch to work on it this morning hehe. I was just gonna rewrite it. I think for now we should just have a function for each game and then we can abstract it later if it really matters.

**Comment by ChasingLogic** [comment]
I don't think it matters and I think a function per game is a lot of overkill, I'll show you what I have when we meet.

**Comment by ChasingLogic** [comment]
Not relevant any longer.
