### ISSUE TITLE
Switch to Mongoose, get rid of db-utils

### ISSUE THREAD

**Issue by ChasingLogic** [ChasingLogic/cardinal#74]
@growlove found out that Mongoose does a majority of what db-utils does and lets us define our objects up front, makes connecting easy (which it's not with the native driver I'm discovering.) and makes passing shit around really easy. I'm going to switch to it unless you have a major objection?

**Comment by growlove** [comment]
No objections here

**Comment by ChasingLogic** [comment]
Done
